name: whixp
description: Streamline your XMPP messaging with a lightweight Dart-based XMPP client
version: 2.1.3
repository: https://github.com/vsevex/whixp
issue_tracker: https://github.com/vsevex/whixp/issues
topics: [xmpp, network, socket]

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  connecta: ^1.2.0
  crypto: ^3.0.3
  dnsolve: ^1.0.0
  hive: ^2.2.3
  memoize: ^3.0.0
  synchronized: ^3.1.0+1
  unorm_dart: ^0.3.0
  xml: ^6.5.0

dev_dependencies:
  convert: ^3.1.1
  lint: ^2.3.0
  test: ^1.25.2

platforms:
  android:
  ios:
  macos:
  windows:
